# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

examples/get-started/blink:
  disable_test:
    - if: IDF_TARGET not in ["esp32", "esp32c3"]
      temporary: true
      reason: lack of runners
